export default function About() {
  return (
    <main class="text-center text-white p-[0.1rem]">
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos ullam minus sint odio. Soluta nulla, ipsum quos minima tempora vero facere unde! Voluptatem et mollitia molestiae corrupti! Velit, itaque quis.
    Doloribus facilis praesentium totam. Laudantium similique dolorem enim et, sed optio eligendi voluptatum ex necessitatibus cupiditate repellendus perspiciatis repellat dignissimos! Qui facilis incidunt inventore voluptatum cumque facere nam quos nulla?
    Tenetur facere nostrum rem error earum, eum, quas maxime suscipit maiores excepturi facilis pariatur eaque sapiente ex officia consequuntur autem neque magni eveniet optio illum molestiae dolorum. Possimus, ducimus at?
    Aperiam voluptatibus ex molestiae in eaque eveniet dolore sed sit et? Facilis culpa consequatur fuga amet blanditiis ipsum? Nam cum fugiat deleniti, dolorum obcaecati quae molestiae harum possimus omnis assumenda!
    Repellat doloribus minima, natus dolorem velit quaerat tenetur quis ullam, ad ex nesciunt facilis inventore quae quos necessitatibus animi. Eveniet inventore perspiciatis nobis dignissimos maiores cum saepe deserunt corporis mollitia?
    Aliquid voluptatibus tempore totam accusamus neque incidunt asperiores ad? Accusantium praesentium possimus optio quisquam adipisci exercitationem voluptates earum commodi ipsa assumenda iste corrupti consequuntur quas magnam excepturi, voluptas nesciunt nemo.
    Rerum quas, magnam deleniti obcaecati minus perspiciatis itaque sit repudiandae. Ducimus dolores accusantium unde consequatur rerum tempore? Quisquam, corporis ut numquam, dolore accusamus incidunt, repellendus culpa delectus soluta id eligendi!
    Adipisci consequuntur est dolores qui reprehenderit vel nobis, odit voluptate nostrum, placeat rem? Ducimus soluta iste nam nostrum quae aut culpa a fugit minima, recusandae, labore excepturi assumenda laborum velit.
    Iure, maiores? Saepe, natus. Quaerat accusantium perferendis exercitationem nisi ipsum est, reiciendis excepturi dolorem! Nemo harum fugiat, officiis cum architecto voluptatibus omnis magnam, odio expedita deserunt voluptatem laboriosam vero alias.
    Distinctio porro odio natus eos ipsum voluptas rerum sapiente molestiae, laboriosam cum explicabo perferendis libero! Facere placeat et, nemo natus quam nesciunt voluptate tempora ea voluptatum fugit dolorum! Doloremque, labore.
    Eius, quas hic. Omnis, inventore? Sequi aliquid velit sint reiciendis, quisquam ut in nemo beatae expedita mollitia molestias eum porro ratione, dolorum iusto ipsam, accusamus nihil voluptatum a nam tempore?
    Corporis commodi sapiente tenetur animi earum asperiores quos deleniti distinctio adipisci blanditiis? Incidunt cum debitis ut natus quod officia laudantium, harum ipsum assumenda aliquam. Ea amet saepe ad ducimus voluptatem.
    Magni magnam, officiis rem, ea perferendis voluptas ab libero non tempora est eum minus aliquid autem sunt vel nulla dignissimos consequatur tenetur dolores deserunt nostrum ratione. Repudiandae quisquam fuga exercitationem.
    Ipsa vel, rerum quae architecto suscipit ab adipisci ipsum voluptate distinctio quo culpa unde vero dicta omnis, inventore placeat reprehenderit quod voluptas molestias! Alias, ipsum! Fugit enim dolor at illum.
    Eum voluptatum molestiae accusantium quaerat magni facere autem sit eveniet nulla alias at quis consequatur delectus atque porro voluptates sequi impedit quos, dolorum recusandae perferendis iure. Quibusdam quam inventore debitis!
    Quaerat sequi totam voluptas natus vitae, voluptatum, eligendi necessitatibus temporibus dignissimos voluptatem fugiat modi impedit ut ad corporis reprehenderit rerum? Quia ipsum nostrum nobis eligendi rerum dicta reiciendis quos pariatur?
    Minus laboriosam repellendus vitae tempore! Reiciendis in fuga tempora recusandae nemo ipsam deserunt quam consequuntur, minus voluptate sint aliquam ea eos soluta molestias perferendis eaque sapiente dolorum officia. Adipisci, nostrum?
    Nemo ex dolorem illum repudiandae possimus odio fugiat officia. Deleniti omnis cumque sint animi laborum, ullam similique placeat voluptates dolorem quaerat consequatur, voluptatum doloribus delectus nemo repellendus dolorum id non.
    Dignissimos assumenda fugit illum cum consectetur similique aliquid expedita qui quaerat. Dignissimos corporis temporibus necessitatibus aliquam nulla distinctio! Quibusdam mollitia quia voluptas repudiandae, velit atque deleniti aliquid? Eos, expedita ut.
    Nobis, aliquid? Quas placeat magni aperiam? Iure incidunt excepturi maxime aperiam debitis sequi id quidem cupiditate, eveniet nulla doloremque impedit praesentium quos deleniti sunt ut, dolore, tempora alias saepe quod.
    Culpa repudiandae, minima placeat voluptatum doloremque maxime cum perferendis totam non ipsam a laborum praesentium doloribus sit quaerat laudantium ex repellat in earum officia unde modi. Reprehenderit corporis iste commodi.
    Provident aperiam nobis minima? Ea earum commodi consequuntur quo blanditiis id fugiat quam perferendis. Praesentium maiores facere quia saepe et, placeat pariatur odio voluptatum sint ex hic fugiat a nostrum.
    Suscipit laudantium aut obcaecati dolore explicabo debitis. Cum, dolore. Tempora iure nulla suscipit tenetur a porro modi autem corrupti sequi ducimus nostrum explicabo ipsa similique, maiores soluta aspernatur assumenda obcaecati.
    Iure eius, inventore voluptatem saepe nulla et minima, nobis facere illum assumenda molestias nemo ex! Aperiam deserunt ducimus ex vero totam necessitatibus ut qui facilis odio saepe? Cupiditate, eos nam!
    Impedit repellat molestias aut accusantium. Ducimus, nemo minus natus harum perspiciatis delectus cupiditate velit quisquam animi sunt fugiat reprehenderit a, eaque tempora quia facere consectetur eius repellat esse. Culpa, quae.
    Repellendus itaque nam hic adipisci voluptatum in tenetur ratione dolorem ipsum. Excepturi cum vitae nesciunt consequuntur? Aliquam quos dignissimos eaque repellat tempore esse sunt blanditiis provident perspiciatis? Beatae, sit provident?
    Eligendi soluta quod ea aut quasi, deleniti reiciendis et eos nemo aliquam alias obcaecati repellendus asperiores eum voluptas numquam, earum corrupti reprehenderit delectus distinctio. Sequi corrupti at iure adipisci. Ex?
    Facilis sed itaque amet animi libero commodi quisquam officia? Provident hic dolor suscipit libero iste ad illo, mollitia nisi omnis esse perspiciatis quia ab, ex quaerat error exercitationem nobis eius?
    Quaerat nulla ratione optio quisquam vero? Praesentium ex aperiam consectetur esse quisquam cum ad fuga voluptate inventore saepe, ut natus dolorem. Ipsam soluta voluptatem, suscipit esse perspiciatis nemo similique hic.
    Maiores neque nesciunt cupiditate dolores incidunt culpa enim vitae mollitia reiciendis quaerat delectus voluptatum dolorum officia adipisci saepe quam hic, voluptatibus sequi. Quo est magni ab saepe asperiores ipsam quam?
    Autem cupiditate commodi exercitationem fuga, atque impedit, cum nesciunt dolorem nemo dolor ea corrupti quae minima incidunt sunt fugit maiores? Ab accusamus architecto amet illo dolorem, animi totam eaque? Quasi!
    Itaque eum debitis repudiandae ad. Qui obcaecati aspernatur veritatis, consequatur accusantium facilis animi quos, tenetur perspiciatis quam numquam! Aperiam, ducimus minus? Eveniet ullam a ducimus nemo illum est iure accusantium?
    Repellat ullam corporis at dolorem rem assumenda quae qui id soluta aliquam expedita minus delectus quas sequi totam dolorum, aut magni! Qui ullam laudantium repellendus expedita, hic tenetur optio numquam.
    Accusantium laboriosam enim, placeat, voluptate itaque sed deleniti tempora rem, illo minima eaque repellat vel ut optio odit quaerat inventore labore illum quis! Porro ipsam, voluptatum eveniet quasi nemo quia.
    Expedita vel minima molestias commodi enim nisi provident? Ipsum, recusandae. Odio eius quos itaque iste, eos delectus nisi aperiam commodi praesentium! Accusantium nesciunt neque non aut ipsum sapiente iusto nostrum.
    Odit doloremque eos animi repudiandae, hic culpa veniam quos soluta? Optio quod, repellat iure nostrum quae, fugiat qui veniam vero temporibus velit minus, reiciendis corrupti in exercitationem similique rerum molestias!
    Quia rerum facilis ab, quibusdam eaque, quas corrupti nostrum exercitationem magni a eos, commodi aperiam ut velit pariatur obcaecati quidem asperiores hic fuga! Dicta dolore, sint cumque ducimus ratione facere!
    Necessitatibus placeat ipsam commodi distinctio optio quasi perspiciatis earum eius cum reiciendis recusandae iure animi officia nulla facilis maiores ad nihil magnam aliquid hic, est impedit quidem quae? Necessitatibus, animi.
    Rem, reiciendis eius sit ipsam ipsa sunt molestias quas ducimus possimus quod quia, quisquam numquam aliquam iusto. Quod magnam quasi quidem laboriosam unde, laborum fugiat reiciendis sunt. Nemo, voluptatem quia?
    Sed officiis neque est ullam quasi sint cupiditate omnis veritatis esse deleniti perspiciatis ea consequatur magnam facere, reprehenderit magni ratione, assumenda in rem ducimus exercitationem. Deserunt ipsa qui iste soluta!
    Hic repellendus dolore tempora architecto dignissimos sunt consectetur minima, modi nostrum aliquam cum ducimus unde reprehenderit quo temporibus consequatur ex explicabo debitis, placeat deserunt quibusdam! Temporibus accusantium dolor animi veritatis.
    Dolores voluptatum aspernatur totam obcaecati consequuntur aut! Quasi nesciunt laboriosam ipsam consequatur labore mollitia officiis? Sint molestiae magni fugit dolorum voluptate? Provident quaerat modi molestiae debitis odit laudantium eligendi id.
    At beatae aperiam molestias unde error voluptas ullam sapiente deserunt. Quasi tempore consectetur corporis animi molestias quam doloremque atque iusto tenetur error? Rem consequuntur et suscipit deleniti, tempore ad at.
    Odio numquam consectetur facere qui, eveniet rerum ducimus minima ad obcaecati. Aut atque perspiciatis totam laboriosam eum, quasi tempora eveniet. Molestiae illo dolorum totam, sunt dolorem officia distinctio explicabo modi.
    Natus velit voluptate, reprehenderit vel incidunt labore aut perspiciatis, quaerat quidem rerum similique illo. Ab eligendi atque, nostrum quod odit hic laborum beatae earum illo adipisci accusamus, libero et dolorem?
    Iure rem reiciendis earum ex temporibus praesentium illo dolore minus voluptatibus ullam libero amet blanditiis distinctio accusamus quasi facilis officiis expedita impedit, dolorem voluptatem corporis eum. Nisi neque ipsa reprehenderit!
    Cupiditate, ipsum! Neque, ducimus. Reiciendis optio qui rem cupiditate soluta aspernatur minima est eveniet ex eaque? Provident similique exercitationem corrupti ratione vel minima nulla neque veritatis ab cumque. Doloremque, ipsam!
    Aspernatur, veritatis. Et minima harum, libero, amet sequi ad voluptate distinctio, vel vitae corporis possimus enim. Odit, expedita excepturi cupiditate iste, at inventore sint iusto atque, voluptatem omnis voluptate et.
    Error sequi iusto debitis vero deserunt sunt magnam quo, alias veniam dolorem omnis, harum dignissimos voluptate nam quas eos id cum quaerat optio incidunt eveniet excepturi quae quos aspernatur. Illum!
    Possimus vero ipsum ab, temporibus officiis, dolores ipsa veniam quae hic cupiditate voluptates libero non iusto, saepe quas accusamus debitis nostrum nobis sit harum? Quos, pariatur. Id exercitationem ipsam commodi.
    </p>
  </main>
  );
}
